version: 2
vms:
  - name: "linux-x86"
    box: "bento/ubuntu-16.04-i386"
    box_version: "2.3.5"
    os_type: "linux"
  - name: "linux-x86_64"
    box: "bento/ubuntu-16.04"
    box_version: "2.3.5"
    os_type: "linux"
  - name: "macos-x86_64"
    box: "visualnacert/macos"
    box_version: "10.12.1"
    os_type: "macos"
  - name: "windows-x86"
    box: "inclusivedesign/windows10-eval-x64"
    box_version: "2017.05.05"
    os_type: "windows"
  - name: "windows-x86_64"
    box: "inclusivedesign/windows10-eval-x64"
    box_version: "2017.05.05"
    os_type: "windows"
